name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.1", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        machineTag: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}
        ignoreCache: true

    - uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: test lua
      run: lua -e 'print("hi from lua")'

